#!/bin/sh -e

echo "Building New LearnOpenGL"

echo "Install deps"

stb_image='./include/stb_image.h'
if [ ! -f $stb_image ]; then
    wget https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -P ./include
fi

make uninstall
make clean
make
